name: yha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  shared_preferences: ^2.3.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  flutter_bloc: ^8.1.3
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  uuid: ^4.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8+4
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fruit.jpg